# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 06:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160626_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='appUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AppUser', verbose_name='App User'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null='True', unique=True, verbose_name='Mobile Phone Number'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='parenthood',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Child', to='users.AppUser', verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='parenthood',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='users.AppUser', verbose_name='Parent'),
        ),
    ]
