# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160627_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
