# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
