# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_appuser_validated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='token',
            new_name='validationCode',
        ),
    ]
