# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160628_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='validationCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
