# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20160629_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='emailValidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='mailToken',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
