# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160629_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='parenthood',
            name='validatedByParent',
            field=models.BooleanField(default=False),
        ),
    ]
