# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_parenthood_validatedbyparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parenthood',
            name='validatedByParent',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', ''), ('denied', 'Denied')], default=False, max_length=10),
        ),
    ]
