# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20160629_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
