# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20160627_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskDescription', models.TextField(verbose_name='Description')),
                ('DateAcomplished', models.DateField(default=0, verbose_name='Date Accomplished')),
                ('taskUplineAccept', models.BooleanField(verbose_name='Upline Accepted')),
                ('taskstatus', models.BooleanField(verbose_name='Task Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AppUser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Task 1',
                'verbose_name_plural': 'Task 1',
            },
        ),
    ]
