# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20160702_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='examScore',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exam Score'),
        ),
    ]
