# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20160702_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='accepted',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('denied', 'Denied')], default=False, max_length=20, verbose_name='Accept'),
        ),
    ]
