# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20160711_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='accepted',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Accept'),
        ),
    ]
